swagger: "2.0"
info:
  description: A REST-ful API for pizza ordering.
  version: "1.0"
  title: Order Pizza API
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /orders:
    get:
      operationId: orders.read_all
      tags:
        - Orders
      summary: Return list of Pizza orders
      description: Read the entire set of orders, sorted by timestamp.
      responses:
        200:
          description: Successfully read orders set operation
          schema:
            type: array
            items:
              properties:
                Table_No:
                  type: integer
                  description: Customer's table number
                Order_ID:
                  type: integer
                  description: Id of the order
                Flavor:
                  type: string
                  description: Flavor of the pizza
                Crust:
                  type: string
                  description: Crust for the pizza
                Size:
                  type: string
                  description: Size of the pizza
                Timestamp:
                  type: string
                  description: Creation/Update timestamp of the order

    post:
      operationId: orders.create
      tags:
        - Orders
      summary: Create an order
      description: Create a new person
      parameters:
        - name: order
          in: body
          description: Order to create
          required: True
          schema:
            type: object
            properties:
              Table_No:
                type: integer
                description: Customer's table number
              Flavor:
                type: string
                description: Flavor of the pizza
              Crust:
                type: string
                description: Crust for the pizza
              Size:
                type: string
                description: Size of the pizza
      responses:
        201:
          description: Successfully created order
          schema:
            properties:
              Table_No:
                type: integer
                description: Customer's table number
              Order_ID:
                type: integer
                description: Id of the order
              Flavor:
                type: string
                description: Flavor of the pizza
              Crust:
                type: string
                description: Crust for the pizza
              Size:
                type: string
                description: Size of the pizza
              Timestamp:
                type: string
                description: Creation/Update timestamp of the order

  /orders/{Order_ID}:
        delete:
              operationId: orders.delete
              tags:
                - Order
              summary: Delete an order from the orders list
              description: Delete an order
              parameters:
                - name: Order_ID
                  in: path
                  type: integer
                  description: ID of order to delete
                  required: true
              responses:
                200:
                  description: Successfully deleted an order
